### ISSUE TITLE
Use helm-source to define sources

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm-system-packages#1]
Hello @ambrevar you should now have access to helm-gentoo.
A first fix would be to define sources with helm-build-* macros.
Let me know if you can't push your changes.
Thanks.

**Comment by Ambrevar** [comment]
Back to work! :) I've updated the package, it should not be too long before it comes back to maturity.

I cannot push the changes however:

> ERROR: Permission to emacs-helm/helm-gentoo.git denied to Ambrevar.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Back to work! :) I've updated the package, it should not be too long before it comes back to maturity.
>
> I cannot push the changes however:
>
>     ERROR: Permission to emacs-helm/helm-gentoo.git denied to Ambrevar.

I granted you admin right like in helm-exwm, you should be able to push
now.
    

-- 
Thierry

**Comment by Ambrevar** [comment]
Nope, same error.

**Comment by thierryvolpiatto** [comment]
Hmm, are you sure you didn't cloned with https address of repo ?
You have the same rights as for helm-exwm, so if you can push there you should be able to push here as well.

**Comment by Ambrevar** [comment]
Don't know what's wrong, here is the remote:
```
remote.origin.url=git@github.com:emacs-helm/helm-gentoo.git
```

I can push to Helm-EXWM.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Don't know what's wrong, here is the remote:
>
> remote.origin.url=git@github.com:emacs-helm/helm-gentoo.git
>
> I can push to Helm-EXWM.

Oh, I think you forget to reply to one of your messages, if you find it
reply to it otherwise perhaps try to click on this link:

https://github.com/emacs-helm/helm-gentoo/invitations

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Here what I see from my side:

![capture d ecran_2017-12-10_20-16-51](https://user-images.githubusercontent.com/1533939/33808490-b9f63bec-dde7-11e7-952f-0c694157d81f.png)

**Comment by Ambrevar** [comment]
Indeed, I missed that.  Problem solved!

I've just pushed an initial revamp, the basics work now.  Let me know if there is anything you'd suggest or you'd like to improve.
