### ISSUE TITLE
Using Eshell with dpkg noninteractive mode

### ISSUE THREAD

**Issue by dvzubarev** [emacs-helm/helm-system-packages#10]
Hi, thank you for the wonderful  package!
It is possible to disable interactive prompts of dpkg with the following command:
`sudo DEBIAN_FRONTEND=noninteractive apt-get -q install  postfix`
I tried it in eshell and it worked fine. If you don't want to disable interactive mode of dpkg by default, there is a possibility to add an option for running dpkg non-interactively in eshell. I can create a PR, if you are interested in this feature.

**Comment by dvzubarev** [comment]
Actually, it is even better to use readline interface. `sudo DEBIAN_FRONTEND=readline apt-get -q install    postfix`. It prompts user via readline and it works in eshell fine for me.

**Comment by Ambrevar** [comment]
Excellent!  Thank you for this.

As I don't have access to a dpkg-based system at the moment, a PR would be very welcome.
Let me know if you need help.

To reflect what is currently done with pacman:

- Let's use `DEBIAN_FRONTEND=readline` by default for all operations and trash the `term-mode` code.

- If `helm-system-packages-dpkg-confirm-p` is nil, then use `DEBIAN_FRONTEND=noninteractive` instead.
