### ISSUE TITLE
Consider making 3 separate packages for Melpa

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm-system-packages#13]
Hi,
I think many people need only one of dpkg, pacman or gentoo, perhaps you could make separate packages in addition of helm-system-packages (all).
It is easy, you just have to create new recipe files for Melpa specifying the files to use and submit PR for each of them.
Thanks.

**Comment by Ambrevar** [comment]
I believe one of the core feature of `helm-system-packages` is to provide a universal, consistent interface to package management without having to worry about the underlying packager manager.

What would be the benefit of splitting?  Saving bandwidth?  It's very little to be honest.
(Also note that I've done some significant refactoring recently, files have gone smaller, and there is still some work to do on portage / dpkg.)

If we provide separate packages, this would be additional burden on MELPA and could add some (admittedly little) confusion on the user side.

Say some users just get 2 managers, e.g. `helm-system-packages-pacman` on one system, then `helm-system-packages-portage` on another.  They could be tempted to write their own wrapper to auto-detect which manager is running on the system.  If they had sticked to the full version, they would not even have raised the issue.

**Comment by Ambrevar** [comment]
I've pushed a work-in-progress support for TRAMP, which means that Helm System Packages is expected to work on remote machines now.  It's a kickass feature and we can't get it if we split the package.  So I'll close this for now.
