### ISSUE TITLE
Persistent action is useless with org buffer folded

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm-system-packages#17]
When hitting C-j on "git" package for example, only top node (*git) is shown making persistent action useless.
Perhaps using `org-cycle` in `helm-system-packages-show-information` would fix problem.
But I wonder why you are using org-mode in there when there is only one node, is it really useful ?

**Comment by Ambrevar** [comment]
I've been wanting to fix this for a while.

My suggestion:
- When pressing `RET`, I want to display information of the _marked_ packages.
- When pressing `C-j` (persistent action), I want to display information of the current package.

How do I distinguish between the two?  Should the persistent action be a different function?

**Comment by Ambrevar** [comment]
54653bd8effd9c2ba196dca32c3dd4774abd003c fixes your issue.
a5db066844389b71287ffb30617e48b6bc481226 fixes mine. I've basically used the

```
      (if helm-in-persistent-action
          (list candidate)
        (helm-marked-candidates))
```

construct.  Is this helm-idiomatic?
