### ISSUE TITLE
Generic package: helm-portage and helm-package-manager

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-system-packages#2]
The current code deals with `portage`, not with the Gentoo specifics, so I think we should rename this package to `helm-portage`, a name which would make more sense on portage-based distributions that are not Gentoo.

More generally, maybe we should anticipate the growth of this package regarding other package managers.
I'd like to add support for Arch Linux' `pacman` in particular.
In that case, I suggest we rename the repo/project to `helm-package-manager`, while individual files would be named after their respective package manager, e.g. `helm-pacman`, `helm-portage`, etc.

What do you think?
@thierryvolpiatto

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> The current code deals with portage, not with the Gentoo specifics, so
> I think we should rename this package to helm-portage, a name that
> would make more sense on portage-based distributions that are not
> Gentoo.
>
> More generally, maybe we should anticipate the growth of this package
> regarding other package managers.  I'd like to add support for Arch
> Linux' pacman in particular.  In that case, I suggest we rename the
> repo/project to helm-package-manager, while individual files would be
> named after their respective package manager, e.g. helm-pacman,
> helm-portage, etc.
>
> What do you think?

Looks a good idea.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> The current code deals with portage, not with the Gentoo specifics, so I think we should rename this package to helm-portage, a name that would make more
> sense on portage-based distributions that are not Gentoo.
>
> More generally, maybe we should anticipate the growth of this package regarding other package managers.
> I'd like to add support for Arch Linux' pacman in particular.
> In that case, I suggest we rename the repo/project to helm-package-manager, while individual files would be named after their respective package manager,
> e.g. helm-pacman, helm-portage, etc.
>
> What do you think?

OTOH this force people to load files for several system when only one is
needed (Arch users don't need portage and gentoo users have no use of Pacman).

-- 
Thierry

**Comment by Ambrevar** [comment]
It forces to download them but not to `require` them.

Considering the files should be no more than 10k, is this really a big deal?

Besides we could have a `helm-package-manager` function that detects the system and fires up the appropriate code.
For users running several different systems, that would simplify the setup.

**Comment by Ambrevar** [comment]
What do you think of the name `helm-packages`?  It could be confused with Emacs packages though.  So what about `helm-system-packages` then?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> What do you think of the name helm-packages? It could be confused with
> Emacs packages though. So what about helm-system-packages then?

Yes looks good.

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by Ambrevar** [comment]
`helm-system-packages` will yield a long namespace.  I don't think it's wise to go for abbreviations however (`helm-syspackages` or `helm-syspkg` are a bit too cryptic in my opinion).

I don't think I have the rights to rename the repository.  Could you do it with whatever you think is most appropriate?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> helm-system-packages will yield a long namespace. I don't think it's wise to go for abbreviations however (helm-syspackages or helm-syspkg are a bit too cryptic in my
> opinion).
>
> I don't think I have the rights to rename the repository.

Did you try, I think you should be able to do this as you have admin rights.

> Could you do it with whatever you think is most appropriate?

I you can't I will do it, have a try first.


-- 
Thierry

**Comment by Ambrevar** [comment]
I did, the button "Rename" is greyed out.

Makes sense to me: I only administrate the repo, not the Emacs-Helm user: I should not be able to rename it to anything the owner of Emacs-Helm would not want, right? :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I did, the button "Rename" is greyed out.

Even if you edit the form ?
It is greyed for me until I delete the "o" of gentoo.

> Makes sense to me: I only administrate the repo, not the Emacs-Helm
> user: I should not be able to rename it to anything the owner of
> Emacs-Helm would not want, right?  :)

Yes maybe.

So lets find a name now, if we use helm-system-packages, you don't
forcibly have to prefix your names with helm-system-packages, you can
add at start of helm-system-packages.el a group like helm-sys-pkg and
prefix all with this, e.g. (defun helm-sys-pkg-do-this ())

--
Thierry

**Comment by Ambrevar** [comment]
I think sticking to the same name is easier on the user side.

With a command named `helm-sys-pkg`, if the user invokes `M-x packages` it will not return the command.
The more explicit the better I believe.

**Comment by Ambrevar** [comment]
> It is greyed for me until I delete the "o" of gentoo.

It remains grey for me.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I think sticking to the same name is easier on the user side.
>
> With a command named helm-sys-pkg, if the user invokes M-x packages it
> will not return the command.

You could create aliases for the main commands?

> The more explicit the better I believe.

Well, I hardly see how we can be explicit without having a moderated
long name like helm-system-packages or helm-package-manager.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> It remains grey for me.

Ok, as soon as you have a name, let me know and I will do the change.


-- 
Thierry

**Comment by Ambrevar** [comment]
> You could create aliases for the main commands?

That would violate the namespacing policy though.

> Well, I hardly see how we can be explicit without having a moderated
> long name like helm-system-packages or helm-package-manager.

Absolutely, never said the opposite :)

Let's go for helm-system-packages.

**Comment by Ambrevar** [comment]
My bad, it was a browser incompatibility: I just renamed the repo!
