### ISSUE TITLE
Find files in packages

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-system-packages#3]
Currently the "Find files" action only outputs the files in a buffer.
It would be much more useful to chain the action with another Helm session in which we could choose which files to "find".

This would be similar to what is currently done for URL:

        (browse-url (helm-comp-read "URL: " urls :must-match t))))))

Is there such a Helm interface that can take an arbitrary list of files as argument?
I'd like to have the actions of Helm Find Files in that session.

@thierryvolpiatto?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Currently the "Find files" action only outputs the files in a buffer.
> It would be much more useful to chain the action with another Helm session in which we could choose which files to "find".
>
> This would be similar to what is currently done for URL:
>
>     (browse-url (helm-comp-read "URL: " urls :must-match t))))))
>
> Is there such a Helm interface that can take an arbitrary list of files as argument?
> I'd like to have the actions of Helm Find Files in that session.

Not sure to understand what you want here, but helm-find-files is
available in any helm-session by hitting C-x C-f (except in hff itself
of course).

-- 
Thierry

**Comment by Ambrevar** [comment]
No that's not it.

`helm-system-packages` lists the packages.  One action is "Find files" which dumps to a buffer all the filenames of the marked packages.

I want to change that behaviour so that instead of outputting a raw list of files, it fires up a new Helm session over that list of files.
The Helm session would have the same actions as `helm-find-files`, more or less.

I cannot use `helm-find-files` directly because it lists the files of some directory.
I want to list specific files only, i.e. the ones belonging to the marked packages.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> No that's not it.
>
> helm-system-packages lists the packages. One action is "Find files"
> which dumps to a buffer all the filenames of the marked packages.

Ok, I see now.

> I want to change that behaviour so that instead of outputting a raw
> list of files, it fires up a new Helm session over that list of files.
> The Helm session would have the same actions as helm-find-files, more
> or less.

Well, you have just to modify the `helm-system-packages-print` function
so that it popup a helm listing files with all actions needed instead of
a simple buffer, should not be too hard.

--
Thierry

**Comment by Ambrevar** [comment]
OK, I was just asking to make sure I'm not re-inventing the wheel.

I'll go for a custom `helm` then.

**Comment by Ambrevar** [comment]
Done.
