### ISSUE TITLE
Using preselect

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-system-packages#4]
I'd like to enable the `:preselect` feature so that the package name at point gets pre-selected.

I thought something along those lines would work.

```
(defun helm-system-packages-dpkg ()
  "Preconfigured `helm' for dpkg."
  (helm :sources '(helm-system-packages-dpkg-source)
        :buffer "*helm dpkg*"
        :preselect (and (thing-at-point 'symbol)
                        (concat "\\_<" (regexp-quote (thing-at-point 'symbol)) "\\_>"))))
```

It does not.  I suspect this might have something to do with the fact that the source is built from
`helm-build-in-buffer-source`.

@thierryvolpiatto?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I'd like to enable the :preselect feature so that the package name at point gets pre-selected.
>
> I thought something along those lines would work.
>
> (defun helm-system-packages-dpkg ()
>   "Preconfigured `helm' for dpkg."
>   (helm :sources '(helm-system-packages-dpkg-source)
>         :buffer "*helm dpkg*"
>         :preselect (and (thing-at-point 'symbol)
>                         (concat "\\_<" (regexp-quote (thing-at-point 'symbol)) "\\_>"))))

Generally avoid repetitions like above by using helm anaphoric macros
(helm-aif, helm-aand etc...)

> It does not.

I see two reasons:

1) Your preselection is beyond the displayed candidates (see
:candidate-number-limit)

2) your regexp is too strict, it matches "python" but not
"python-something-else".

> I suspect this might have something to do with the fact that the
> source is built from helm-build-in-buffer-source.

No.

BTW you don't have to compute yourself the candidates in your init
function:


    (defun helm-system-packages-init ()
      "Cache package lists and create Helm buffer."
      (helm-system-packages-refresh t)
      (helm-init-candidates-in-buffer
          'global
        helm-system-packages--all))

is enough.

-- 
Thierry

**Comment by Ambrevar** [comment]
Sorry the lack of anaphoric control or the bad regexp, that was just quick&dirty code for testing purpose.

> 1) Your preselection is beyond the displayed candidates (see :candidate-number-limit)

That was it!

Thanks for the `helm-system-packages-init` review!

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thanks for the helm-system-packages-init review!

BTW for *-dpkg, perhaps you can have a look at helm-apt.el and a merge
could be done at some point to remove helm-apt.el from helm itself?

-- 
Thierry

**Comment by Ambrevar** [comment]
I completely forgot helm-apt existed...
At first glance I'd say yes, we should merge the two.

I named mine "dpkg" because it's the most central tool, but to be honest I've always been confused by Debian's nomenclature.

I usually don't work with Debian-based systems: it just so happens that I'm stuck with a Ubuntu right now, so I thought why not implement it right away.  It won't last for long though, hopefully I'll have time to perform the merge.

**Comment by Ambrevar** [comment]
Let me know of any feature you'd be missing from my package.

**Comment by Ambrevar** [comment]
Can you explain the code around `helm-apt-default-archs`?  Why do you specify the architecture in `helm-apt--installed-package-name`?

I'm not sure how dpkg uses of the arch prefix.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Can you explain the code around helm-apt-default-archs? Why do you specify the architecture in helm-apt--installed-package-name?

IIRC some packages have different version depending on arch
e.g. foo:i386 or foo:amd64 but when you install the package you install
the package foo and the package manager (apt) decide which package to
install depending your architecture.
We have to filter such packages to make them appearing as installed (if
they are of course) otherwise they are not found and they appear as
uninstalled even if they are.

-- 
Thierry

**Comment by Ambrevar** [comment]
OK.  Let's follow up with this on #5 .
