### ISSUE TITLE
Integrate helm-apt

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-system-packages#5]
helm-apt has some features that might be lacking in helm-system-packages:

- Support for packages with different architectures.
- Support for filtered subset of packages.
- Force re-install.

Things I'm not really willing to integrate:

- Purge package: I think this is a misfeature of `dpkg`.  Configuration files should not be "purged" when the user does not really know what this does.

@thierryvolpiatto: Opinion?  Anything else?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> helm-apt has some features that might be lacking in helm-system-packages:
>
>   * Support for packages with different architectures.

I think we already have this, no?

>   * Support for filtered subset of packages.

Don't understand this.

>   * Force re-install.

We have this.

>
> Things I'm not really willing to integrate:
>
>   * Purge package: I think this is a misfeature of dpkg. Configuration
>   files should not be "purged" when the user does not really know what
>   this does.

Purge package is needed.

--
Thierry

**Comment by Ambrevar** [comment]
>   * Support for packages with different architectures.
> I think we already have this, no?

No we don't, why do you think we do?

>    * Support for filtered subset of packages.
> Don't understand this.

Basically these bindings

> (defvar helm-apt-map
>   (let ((map (make-sparse-keymap)))
>     (set-keymap-parent map helm-map)
>     (define-key map (kbd "M-I")   'helm-apt-show-only-installed)
>     (define-key map (kbd "M-U")   'helm-apt-show-only-not-installed)
>     (define-key map (kbd "M-D")   'helm-apt-show-only-deinstalled)
>     (define-key map (kbd "M-A")   'helm-apt-show-all)
>     map))

and the associated code.

>    * Force re-install.
> We have this.

No we don't.  Is there a misunderstanding?  I'm talking about this repo, `helm-system-pacakges`.

> Purge package is needed.

It costs litteraly just 1 action to add it, so it's no problem.
But can you explain the purpose of `apt-get purge`?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>       + Support for packages with different architectures.
>         I think we already have this, no?
>
> No we don't, why do you think we do?

So explain what do you want exactly, and what do you mean by "support
for different architectures".

>       + Support for filtered subset of packages.
>         Don't understand this.
>
> Basically these bindings
>
>     (defvar helm-apt-map
>     (let ((map (make-sparse-keymap)))
>     (set-keymap-parent map helm-map)
>     (define-key map (kbd "M-I") 'helm-apt-show-only-installed)
>     (define-key map (kbd "M-U") 'helm-apt-show-only-not-installed)
>     (define-key map (kbd "M-D") 'helm-apt-show-only-deinstalled)
>     (define-key map (kbd "M-A") 'helm-apt-show-all)
>     map))
>    
> and the associated code.

So yes we have this in helm-apt, where is the problem?

>       + Force re-install.
>         We have this.
>
> No we don't.

Yes we have, you don't see it because it is a filtered action i.e. you
can't reinstall a package not installed.

> Is there a misunderstanding? I'm talking about this repo,
> helm-system-pacakges.

I am talking of helm-apt.

>     Purge package is needed.
>    
> It costs litteraly just 1 action to add it, so it's no problem.
> But can you explain the purpose of apt-get purge?

Well the apt-get man page will explain this better than me, anyway I am
often using this.

-- 
Thierry

**Comment by Ambrevar** [comment]
You misunderstood the original post: I want to list the features that are currently implemented in helm-apt but that are not implemented in helm-system-packages.

The architecture feature refers to the last question in #4.

`apt-get purge`: I do understand that "it removes configuration files"
(http://manpages.ubuntu.com/manpages/wily/man8/apt-get.8.html).
But my point is that it's ill-designed: configuration files should only be removed if the user hasn't touched them.  This is the default behaviour in portage and pacman.
Anyways, neither `apt-get remove` nor `apt-get purge` do the right thing, so I'll add them both.

**Comment by Ambrevar** [comment]
Also my fuss around `apt-get purge` is irrelevant to this package: sorry if I seemed to steer away from the matter at hand.  I was simply genuinely curious about how dpkg users handle the removal process.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> configuration files should only be removed if the user hasn't touched
> them.

IIRC apt does this with purge, with remove it inconditionally keep the files.

-- 
Thierry

**Comment by Ambrevar** [comment]
I see, removed-but-not-purged packages also have a special status: they are marked as "residual".  If I integrate the purge action, then I need to use a specific face for residual packages.  It should not be a problem.

**Comment by Ambrevar** [comment]
I see now that dpkg supports installing several architecture in parallel.
Because of that, the Helm buffer should contain the architecture suffix of installed packages as returned by `dpkg --get-selections`.

**Comment by Ambrevar** [comment]
I've added support for matching descriptions.
I've pushed the changes to a separate branch (bufferdesc) as I'm afraid I might have broken some package managers by doing so.

pacman seems to work well.

@thierryvolpiatto: If you have a system running dpkg/apt, could you give the branch a try and see if the following works as expected:
- fontification (including of residual packages)
- description matching (not just the coloring)
- different architectures

If so, then I suppose helm-apt can be safely removed from Helm.

I'll add category filtering later (the "M-U" bindings and so on).

**Comment by Ambrevar** [comment]
I've added the category filters.  Note that they are togglers now, which makes it possible to display select categories at the same time, e.g. dependencies and installed packages without non-installed packages.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>   * fontification (including of residual packages)

Seems package installed are colorized in orange
(font-lock-comment-face?), however there is no way to filter them (as in
helm-apt).

>   * description matching (not just the coloring)

If you mean pattern matching description, no it is not working.

>   * different architectures

Dunno what you mean, what should I test here?

Also some other comments:

* Why using seq library when you can do the same with cl-loop ?

* You are requiring helm-files which is very costly, is it really
necessary ?

* The description buffer is writable, it should be read-only (inherit
from special-mode)

* The actions should be in a defcustom (optional).

* Looks like you are handling dependencies for package deletion, it is
not necessary as user can use autoremove afterward if needed.

* Perhaps add a help section (C-h m)

--
Thierry

**Comment by Ambrevar** [comment]
Are you sure you checked out the `bufferdesc` branch?
Does helm-dpkg run through `helm-system-packages-dpkg-transformer`?

**Comment by thierryvolpiatto** [comment]
Also I see you are using eshell to install/uninstall etc..., the problem
with eshell is that it is a pseudo terminal where you have to type again
sudo password at each command (well I use a workaround for this but it
is not common), also the terminal is not fully functional for some
interactive operations.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Are you sure you checked out the bufferdesc branch?

No, sorry I forget to switch to this branch, however with this branch I
have an empty buffer, no candidates.

-- 
Thierry

**Comment by Ambrevar** [comment]
Then there must be an issue with an issue with the init part.
Can you check if `helm-system-packages-dpkg-refresh` is run?

**Comment by Ambrevar** [comment]
The error is most probably in `helm-system-packages-dpkg-buffer-descriptions`, which is the part I cannot debug without a `apt-cache search .` output.

**Comment by Ambrevar** [comment]
>    * different architectures
> Dunno what you mean, what should I test here?

Some packages are suffixed with `:amd64` or `:i386` or something like that.
Could you make sure they appear in the list and you can display info / install them?

> * Why using seq library when you can do the same with cl-loop ?

Simply because I like it better ;)  Is there any drawback?
It's used only once in the entry point function, in a trivial way.

> * You are requiring helm-files which is very costly, is it really
> necessary ?

Yes, because it provides one of the most awesome features (in my opinion): run helm-find-files over package file lists.

> * The description buffer is writable, it should be read-only (inherit
> from special-mode)

Well, isn't it a feature, in the end?  Just like Eshell where you can rewrite the output...
Those are throw-away buffers anyways, editing can't hurt.

> * The actions should be in a defcustom (optional).
>
> * Looks like you are handling dependencies for package deletion, it is
> not necessary as user can use autoremove afterward if needed.
>
> * Perhaps add a help section (C-h m)

Will do all that, plus plenty more.
I've got a ton of good stuff to add in there!

> Also I see you are using eshell to install/uninstall etc..., the problem
> with eshell is that it is a pseudo terminal where you have to type again
> sudo password at each command (well I use a workaround for this but it
> is not common), also the terminal is not fully functional for some
> interactive operations.

The sudo password can saved until some timeout.

```
(require 'em-tramp)
(setq password-cache t)
(setq password-cache-expiry 3600)
```

I've used Eshell for pacman, dpkg/apt and emerge and it worked very well for me, at least for the transactions (install/remove), which is the only thing helm-system-packages needs.

True so however, Eshell is severely flawed on Emacs<26 (I've reported a number of issues upstream).  It works much better with 3-4 patches.
See https://github.com/Ambrevar/dotfiles/blob/master/.emacs.d/lisp/patch-eshell.el.
I could backport them in `helm-system-packages` and load them if Emacs version is <26.

What do you think?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>       + different architectures
>         Dunno what you mean, what should I test here?
>
> Some packages are suffixed with :amd64 or :i386 or something like that.
> Could you make sure they appear in the list and you can display info / install them?

Seems they do not appear.

>       + Why using seq library when you can do the same with cl-loop ?
>
> Simply because I like it better ;) Is there any drawback?

Another library to load, incompatibility between versions once installed
etc...

> It's used only once in the entry point function, in a trivial way.
>
>       + You are requiring helm-files which is very costly, is it really
>         necessary ?
>
> Yes, because it provides one of the most awesome features (in my
> opinion): run helm-find-files over package file lists.

Ok, so perhaps you can avoid requiring at load-time ?

>
>       + The description buffer is writable, it should be read-only (inherit
>         from special-mode)
>
> Well, isn't it a feature, in the end? Just like Eshell where you can rewrite the output...
> Those are throw-away buffers anyways, editing can't hurt.

It is annoying, there is no need to edit such buffers and you can't quit
with "q".

>
>       + The actions should be in a defcustom (optional).
>
>       + Looks like you are handling dependencies for package deletion, it is
>         not necessary as user can use autoremove afterward if needed.
>
>       + Perhaps add a help section (C-h m)
>
> Will do all that, plus plenty more.
> I've got a ton of good stuff to add in there!
>
>     Also I see you are using eshell to install/uninstall etc..., the problem
>     with eshell is that it is a pseudo terminal where you have to type again
>     sudo password at each command (well I use a workaround for this but it
>     is not common), also the terminal is not fully functional for some
>     interactive operations.
>
> The sudo password can saved until some timeout.
>
> (require 'em-tramp)
> (setq password-cache t)
> (setq password-cache-expiry 3600)

I would not trust this, but well yes there is several ways to avoid
password in eshell the emacs newcomer will find only after months.

> I've used Eshell for pacman, dpkg/apt and emerge and it worked very
> well for me, at least for the transactions (install/remove), which is
> the only thing helm-system-packages needs.

No when installing you will sometimes be prompted to configure a package
in a dialog (zenity or ncurses or whatever I don't remember), eshell
doesn't fully support this (try to install postfix for example), IIRC
shell have the same problem, it is why I switched to term for apt
operations (I was using eshell initially).

> True so however, Eshell is severely flawed on Emacs<26 (I've reported
> a number of issues upstream). It works much better with 3-4 patches.
> See
> https://github.com/Ambrevar/dotfiles/blob/master/.emacs.d/lisp/patch-eshell.el.
> I could backport them in helm-system-packages and load them if Emacs
> version is <26.
>
> What do you think?

Don't think it is necessary as your patches AFAIU doesn't handle problem
described above.


--
Thierry

**Comment by Ambrevar** [comment]
I've pushed some changes which might have fixed the empty buffer issue.
If it does not, could you send me a relevant excerpt of the output of

```
apt-cache search .
```
and
```
apt-cache pkgnames
```
Thanks!

**Comment by Ambrevar** [comment]
> I would not trust this, but well yes there is several ways to avoid
> password in eshell the emacs newcomer will find only after months.

I'm not sure if there is any security issue related to this package.
Let me know if you come across anything in that area.

I can document the options in the readme.  Eshell is very powerful and has significant advantages over using `term-mode`, it would be a pity to dismiss it.

> No when installing you will sometimes be prompted to configure a package
> in a dialog (zenity or ncurses or whatever I don't remember),

You are right, I completely forgot `dpkg` does that.
What a terrible design... :/

I'll use `term-mode` for `dpkg` then.

**Comment by thierryvolpiatto** [comment]
Still have empty buffer, with this patch it works:

```diff
diff --git a/helm-system-packages-dpkg.el b/helm-system-packages-dpkg.el
index 100bbaf..25dea70 100644
--- a/helm-system-packages-dpkg.el
+++ b/helm-system-packages-dpkg.el
@@ -117,6 +117,7 @@ Requirements:
 (defvar helm-system-packages-dpkg--names nil
   "Cache of all package names.")
 
+(defvar helm-system-packages-dpkg--all nil)
 (defvar helm-system-packages-dpkg--descriptions nil
   "Cache of all package names with descriptions.")
 
@@ -213,7 +214,7 @@ Otherwise display in `helm-system-packages-buffer'."
 
 (defvar helm-system-packages-dpkg-source
   (helm-build-in-buffer-source "dpkg source"
-    :init 'helm-system-packages-init
+    :init 'helm-system-packages-dpkg-init
     :candidate-transformer 'helm-system-packages-dpkg-transformer
     :candidate-number-limit helm-system-packages-candidate-limit
     :display-to-real 'helm-system-packages-extract-name
```
The `:input` thing is really annoying, you should remove it.
It is quite slow to startup even when the caches are set, will look later why, not the time right now.

Thanks.

**Comment by Ambrevar** [comment]
Damn!  Thanks for the catch! :D

I think it was slow because your patch is wrong: you should have renamed `--all` to `--names`, or else the cache would be recreated on every run.

Let me know if it's fast enough now.

**Comment by Ambrevar** [comment]
@thierryvolpiatto: Regarding the info buffer being read-only, what's the best way to make `q` quit considering I want the buffer to be in Org mode?

**Comment by Ambrevar** [comment]
> * Looks like you are handling dependencies for package deletion, it is
> not necessary as user can use autoremove afterward if needed.

Is this still valid with the current code?

The "uninstall" action is driven by
>       (helm-system-packages-run-as-root "apt-get" "remove" (when helm-current-prefix-arg "--auto-remove"))))

The dependencies will be uninstalled only when called with a prefix argument.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> @thierryvolpiatto: Regarding the info buffer being read-only, what's the best way to make q quit considering I want the buffer to be in Org mode?

diff --git a/helm-system-packages.el b/helm-system-packages.el
index 2f153cd..42445b3 100644
--- a/helm-system-packages.el
+++ b/helm-system-packages.el
@@ -99,7 +99,8 @@ such as the package description."
 
 With prefix argument, insert the output at point.
 Otherwise display in `helm-system-packages-buffer'."
-  (let ((res (apply #'helm-system-packages-run command args)))
+  (let ((res (apply #'helm-system-packages-run command args))
+        (inhibit-read-only t))
     (if (string-empty-p res)
         (message "No result")
       (unless helm-current-prefix-arg
@@ -109,7 +110,8 @@ Otherwise display in `helm-system-packages-buffer'."
         ;; This is does not work for pacman which needs a specialized function.
         (setq res (replace-regexp-in-string "\\`.*: " "* " res))
         (setq res (replace-regexp-in-string "\n\n.*: " "\n* " res)))
-      (insert res))))
+      (save-excursion (insert res))
+      (view-mode)))))
 
 (defun helm-system-packages-find-files (command &rest args)
   (require 'helm-files)


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>     I would not trust this, but well yes there is several ways to avoid
>     password in eshell the emacs newcomer will find only after months.
>    
> I'm not sure if there is any security issue related to this package.
> Let me know if you come across anything in that area.
>
> I can document the options in the readme. Eshell is very powerful and has significant advantages over using term-mode, it would be a pity to dismiss it.
>
>     No when installing you will sometimes be prompted to configure a package
>     in a dialog (zenity or ncurses or whatever I don't remember),
>    
> You are right, I completely forgot dpkg does that.
> What a terrible design... :/
>
> I'll use term-mode for dpkg then.

You need it for apt-get too (which is BTW using dpkg):

debconf: Impossible d'initialiser l'interface : Dialog
debconf: (L'interface dialog ne fonctionnera pas avec un terminal rustique (« dumb »), un tampon shell d'Emacs ou sans terminal de contrôle.)
debconf: Utilisation de l'interface Readline en remplacement

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
Yes, of course, with "dpkg" I meant all the transactions in "helm-system-packages-dpkg.el".

**Comment by Ambrevar** [comment]
> debconf: Utilisation de l'interface Readline en remplacement

Doesn't it work with `readline`?

**Comment by Ambrevar** [comment]
I've move dpkg from Eshell to term.  Let me know if that works for you.

Also let me know if there is anything else.  Otherwise I'll merge onto master.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I've move dpkg from Eshell to term. Let me know if that works for you.

Good, it is working.

> Also let me know if there is anything else. Otherwise I'll merge onto master.

`helm-system-packages-print` is not working correctlty, you forgot to
`inhibit-read-only`, so you can display description of one package and
then, unless you delete the buffer you can't write anymore in it because
it is read-only (try C-j on different packages, also here some warnings
you can avoid:

Compile log (compiled async):

In helm-system-packages-dpkg-run-as-root:
helm-system-packages-dpkg.el:79:9:Warning: assignment to free variable
    ‘helm-system-packages-dpkg--names’
helm-system-packages-dpkg.el:80:9:Warning: assignment to free variable
    ‘helm-system-packages-dpkg--descriptions’

In end of data:
helm-system-packages-pacman.el:388:1:Warning: the function ‘org-sort-entries’
    is not known to be defined.

In toplevel form:
helm-system-packages.el:142:1:Warning: Unused lexical variable ‘eshell-buffer-name’

In end of data:
helm-system-packages.el:184:1:Warning: the following functions are not known
    to be defined: eshell-interactive-process, eshell-send-input

Perhaps you can also fix some +80 lines in code source if you want.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Also let me know if there is anything else.

    (unless (or helm-current-prefix-arg helm-system-packages-editable-info-p)
            (view-mode 1))

`helm-system-packages-editable-info-p` and/or prefix arg are not needed,
if one want to edit the description buffer he only have to do `C-x C-q`
(back and forth) once view-mode is enabled.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Otherwise i think you did a pretty good job!

**Comment by Ambrevar** [comment]
> `helm-system-packages-editable-info-p` and/or prefix arg are not needed,
> if one want to edit the description buffer he only have to do `C-x C-q`
> (back and forth) once view-mode is enabled.

Indeed, but I prefer to have them editable directly without any additional keypress, hence the option.

**Comment by Ambrevar** [comment]
I think I've fixed everything else.  I'll merge onto master.
You can proceed with the deletion of helm-apt.  Close this issue when you are done.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I think I've fixed everything else.

Still some warnings:

    In end of data:
    helm-system-packages-pacman.el:393:1:Warning: the function ‘org-sort-entries’
        is not known to be defined.

Use declare-function

    In toplevel form:
    helm-system-packages.el:142:1:Warning: Unused lexical variable ‘eshell-buffer-name’

Probably the variable is indeed not used, didn't look at the code.

    In end of data:
    helm-system-packages.el:185:1:Warning: the following functions are not known
        to be defined: eshell-interactive-process, eshell-send-input

Use declare-function

> I'll merge onto master.  You can proceed with the deletion of
> helm-apt. Close this issue when you are done.

Ok, great thanks.

I will remove helm-apt just before releasing Helm version 2.8.8.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
I wonder what's the best practice to deal with those errors.  Technically, they are false positives since all the mentioned packages are `require`d.

The fault here is to the byte-compiler which fails to find the function definition in the required packages.

I always found `declare-function` to be more of a kludge than a proper way to deal with the issue.

Which command do you use to byte-compile?

>     In toplevel form:
>     helm-system-packages.el:142:1:Warning: Unused lexical variable ‘eshell-buffer-name’
>
> Probably the variable is indeed not used, didn't look at the code.

`eshell-buffer-name` is a defcustom, thus is it dynamically bound.
The `(let ...` is correct: it overrides the Eshell buffer within the scope of the function.
The byte-compiler is wrong here.  How can we solve this issue?  I don't want to resort to a `with-no-warnings`.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I wonder what's the best practice to deal with those errors. Technically, they are false positives since all the mentioned packages are required.
>
> The fault here is to the byte-compiler which fails to find the function definition in the required packages.
>
> I always found declare-function to be more of a kludge than a proper way to deal with the issue.
>
> Which command do you use to byte-compile?

`async-byte-recompile-directory`, this the only correct command to use
to compile all your packages, helm is compiled with this when installed
from Melpa, magit also among others.

>     In toplevel form:
>     helm-system-packages.el:142:1:Warning: Unused lexical variable ‘eshell-buffer-name’
>     
>     Probably the variable is indeed not used, didn't look at the code.
>    
> eshell-buffer-name is a defcustom, thus is it dynamically bound.

Yes once you use eshell, otherwise nobody know (especially the byte
compiler) what this variable is.

> The (let ... is correct:

Yes it is, but as you said the variable is dynamically bound and BTW
need to be declared, otherwise it is interpreted as a lexical var.

> it overrides the Eshell buffer within the scope of the function.  The
> byte-compiler is wrong here.

No it is correct, how can it know anything about eshell ?
So it understand the eshell variable as some lexical binding unused in
your function.

> How can we solve this issue?

If you use defvar with no value as I did, it is perfectly fine, it is
the recommended way to do.
Another way is to require the eshell package handling this, which defeat
all the benefit of its autoloads.

> I don't want to resort to a with-no-warnings.

You don't need to use with-no-warning, see the PR I sent.

-- 
Thierry

**Comment by Ambrevar** [comment]
> Another way is to require the eshell package handling this, which defeat
> all the benefit of its autoloads.

This is what I did: `(require 'esh-mode)` (or `(require 'eshell)`).  This does not shut up the compiler about unused lexical variables.

You've got a point about the autoloads; although I'm not very convinced that forward-declarations are much more maintainable.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>     Another way is to require the eshell package handling this, which defeat
>     all the benefit of its autoloads.
>
> This is what I did: (require 'esh-mode) (or (require 'eshell)). This
> does not shut up the compiler about unused lexical variables.

But you have also to declare the variable, it have to appear physically
in the buffer compiled otherwise the byte compiler don't know about it.
You have the same problem with cl-flet vs flet when you want to modify a
function, the function call should appear physically in the body of cl-flet.

> You've got a point about the autoloads; although I'm not very
> convinced that forward-declarations are much more maintainable.

Don't know what's the problem to add an empty defvar in your source code
when needed.

--
Thierry

**Comment by thierryvolpiatto** [comment]
helm-apt have been dropped from helm, closing now.
